### PR TITLE
more null objects to not get messed up by setters and getters in `Object.prototype`, `JSON` functions are stored separately in vault

### PR DESCRIPTION
**Pull request by xBZZZZ**
post title explains it all

### CODE REVIEW

**Comment by tophf** [comment]
The GM_info object is exposed to userscripts so it should have a standard object shape because userscripts may use standard object methods like hasOwnProperty directly.

JSON.parse and JSON.stringify are own keys from a different JS realm so it cannot be spoofed/broken by the current realm.

I don't see the need for this PR.

**Comment by xBZZZZ** [comment]
> The GM_info object is exposed to userscripts so it should have a standard object shape because userscripts may use standard object methods like hasOwnProperty directly.

but `GM_info.script` is null prototype object and `GM_info.script.hasOwnProperty` will not work (inside userscript)
is that intended?

**Comment by tophf** [comment]
It's an unintentional consequence of using a null prototype in metaCopy for convenience, fixed in 5755efd0, thanks.

**Comment by tophf** [comment]
Hmm, if we use standard object prototype our code can be broken by a hostile page that throws inside the setter so I'll probably rework it...

**Comment by xBZZZZ** [comment]
> JSON.parse and JSON.stringify are own keys from a different JS realm so it cannot be spoofed/broken by the current realm.

note: if web page can get object (array, function, error, object, regexp) from vault's realm it can mess up `JSON`: `object_from_vaults_realm.hasOwnProperty.constructor("JSON.parse='asd';")();`

**Comment by tophf** [comment]
> if web page can get object (array, function, error, object, regexp) from vault's realm

AFAIK it can't. If there is such a way it would make the vault completely meaningless and useless.

**Comment by tophf** [comment]
On the other hand, theoretically the page can do it by using a vulnerability in some popular userscript.
I guess I'll make SafeJSON a prototypeless copy just in case...

**Comment by tophf** [comment]
Or maybe you can reduce this PR to JSON-related changes and I'll merge it.

**Comment by xBZZZZ** [comment]
> Or maybe you can reduce this PR to JSON-related changes and I'll merge it.

I don't think I can do that (I deleted the fork).

**Comment by xBZZZZ** [comment]
> AFAIK it can't. If there is such a way it would make the vault completely meaningless and useless.

only if vault iframe `contentWindow` gets modified before functions are stored in array

**Pull request closed without merging**
