### PR TITLE
Omit cookie in WebDAV requests

### LINKED ISSUE #976: Support: How to debug WebDAV sync issues to Nextcloud instance
### What is the problem?
I can successfully connect to a webdav endpoint of a nextcloud instance with Nautilus, but fail to use it with violentmonkey.

How can I learn more about the error.

It displays `Syncing (1/2)` and the failed.

### How to reproduce it?
1. Have a WebDAV endpoint i.e. a nextcloud instance like https://github.com/bentolor/docker-nextcloud-collabora-postgresql-letsencrypt
2. Set WebDAV and `davs://SERVERNAME/remote.php/dav/files/USERNAME/`  as target
3. Press save

### What is the expected result?
Some syncing happening and files appearing on the webdav target

### What is the actual result?
Only a `Failed` is displayed.

F12 console in Firefox does not provide any output.

### PR DESCRIPTION
**Pull request by gera2ld**
fix #976 

## Changes

- Send internal requests with `fetch`. This affects all requests in Violentmonkey except those sent by `GM_xmlhttpRequest`.
- Omit cookies for WebDAV sync service, bypassing logout/login CSRF protection in NextCloud/OwnCloud. Since we always sent authentication header explicitly in the background, there is no need to worry about CSRF.

## Additional fixes
- Reschedule sync process when sync service is changed.
- Small tweaks on style, to keep the space after colon in languages like English.

### CODE REVIEW

**Comment by tophf** [comment]
Sounds great!
Here's a debug build for @bentolor to test: [vm-debug-8451d5f.zip](https://github.com/violentmonkey/violentmonkey/files/4508167/vm-debug-8451d5f.zip)

**Comment by bentolor** [comment]
Thanks @tophf and @gera2ld for your super-responsive support in this detail matter. I really appreciate this.

Unfortunately the new debug build does not so seem to be successfully in suppressing the cookies. Both requests requests still looks like this and hence the `PROPFIND` fails with the same error.

```
Host: myserver
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0
Accept: */*
Accept-Language: de-DE,de;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Authorization: Basic YmVuOlc2VGpELTZkWUJOLURONVlhLUpCUHNXLUZLbW1D
depth: 1
Origin: moz-extension://01033dd1-0c8b-4258-9c37-8fcfd2f6db2f
Connection: keep-alive
Cookie: __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_username=ben; nc_token=POq3*****; nc_session_id=094523***7; oc3x8sg7kmlk=094523***7; oc_sessionPassphrase=wFZFn*******%2BWk*****O%***CM%2****kQh%2Bta******cC
TE: Trailers
```

As both of you already invested efforts in this issue and to ease up going the last email I emailed you  ready-to-use account data you could use for testing efforts. 

Thanks for your awesome response!

**Comment by gera2ld** [comment]
Sorry, the parameters passed to `fetch` are incorrect, I'm working on it.

**Comment by tophf** [comment]
@bentolor, I've got your message but didn't use it, let's see first if the new version works for you: [vm-b73bb8c.zip](https://github.com/violentmonkey/violentmonkey/files/4521535/vm-b73bb8c.zip)

**Comment by bentolor** [comment]
@tophf Aweseome! Can confirm. Sync immedetialy started to work after updating the temporary loaded addon. Requests also look good to me. Thanks!

**Pull request merged**
