### PR TITLE
fix: set header bar to scrollable for small screen only

### PR DESCRIPTION
**Pull request by gera2ld**
follow-up to #2089

### CODE REVIEW

**Comment by tophf** [comment]
I don't think it helps because mobile devices may be wider than 550px:

image

**Comment by gera2ld** [comment]
When it's wider than 550px, it's still the same as desktop.
When it's smaller than 550px, the header bar will be scrollable, and the dropdown is fixed at `left: 0` same as before.

**Comment by tophf** [comment]
The emulator's width is set to 800px and devicePixelRatio is 1.5, so the ffective width is 533, which is why `@media` fails?

**Comment by tophf** [comment]
Maybe it'd be more reliable to teleport the menu and use position:absolute?

**Comment by gera2ld** [comment]
> Maybe it'd be more reliable to teleport the menu and use position:absolute?

Yes, but that requires a rewrite of component and some more details to deal with (position sync, page overflow).

**Comment by gera2ld** [comment]
Maybe I should check if `header` is scrollable by js instead of using a hard-coded breakpoint?

**Comment by tophf** [comment]
Maybe `flex-wrap: wrap` in the header [for small widths]?

**Comment by tophf** [comment]
>I cannot reproduce what you got above.

Here it is in a desktop version after shrinking the window:

image

**Comment by gera2ld** [comment]
My bad, wrong class name.

```diff
-    .vl-dropdown-right .vl-dropdown-menu {
+    .vl-dropdown-menu {
```

**Comment by tophf** [comment]
LGTM.

**Pull request merged**
