### PR TITLE
feat: add zombieUrl to GM_notification

### LINKED ISSUE #1943: [Feature]  Add `url` property for `GM_notification` to open a new tab on click and make it more persistant.
**Motivation**

```javascript
// ==UserScript==
// @name        New script - github.com
// @namespace   Violentmonkey Scripts
// @match       https://github.com/*
// @grant        GM_notification
// @author      x
// @description 2023/10/28 09:25:14
// ==/UserScript==
'use strict';
let API_URL = "https://example.org/api234";
const cache = {};
setInterval(async () => {
    const item = await fetch(API_URL);
    if (!(item.name in cache) || item.version > cache[item.name]) {
        cache[item.name] = item.version;
        // Hope --> GM_notification(item.name, {url: item.url});
       const ct = GM_notification(item.name, {onclick: () => {window.open(item.url); ct.remove();}}) // Actually
    }
}, 5000);
```
It just push an notification that refer to an URL, it shouldn't be destroyed after the tab close (if using `onclick` event, it will do so).
Using `zombieTimeout` cannot solve this problem, because the function onclick refers to has been destroyed.

**Proposed Solution**

Hope to suppport `url` property. Just like Tampermonkey 5.0.6189 does: https://www.tampermonkey.net/documentation.php#api:GM_notification

**Use Cases**

push news.

我不太会说英语，但是十分感谢开发者们！

### PR DESCRIPTION
**Pull request by tophf**
fixes #1943.

### CODE REVIEW

**Comment by gera2ld** [comment]
Is there an easy way to open a URL on click no matter whether the script is dead?

**Comment by tophf** [comment]
There's no such API.

**Comment by gera2ld** [comment]
But the TM API seems to support that easily:

```js
GM_notification({
  url: OpenUrlNoMatterWhetherScriptIsDead,
});

GM_notification({
  url: OpenOnlyWhenScriptIsDead,
  onclick: e => e.preventDefault(),
});

GM_notification({
  onclick: () => GM_openInTab(OpenUrlOnlyWhenScriptIsNotDead),
});
```

CMIIW

**Comment by tophf** [comment]
As I stated in the issue, I don't like how Tamperonkey implements it:
* it doesn't play well with an already existing solution we provide via zombieTimeout
* using a DOM method preventDefault is super weird by itself and not obvious 
* the name `url` is too generic, it's not obvious what it does

**Comment by gera2ld** [comment]
Reasonable :+1:

**Comment by tophf** [comment]
I wondered if it can generalized as `zombieAction`, but didn't come up with anything other than opening of a URL...

**Pull request merged**
