### PR TITLE
Change injection technique to use src with Blob

### LINKED ISSUE #173: Firefox CSP issue
Firefox does not support script injection from extension when page has CSP restrictions. As a result, no script can be injected to such pages in Firefox. But it works well with Chrome.

Related issues:
#107, #172 

Some examples suffered from this issue:
- scripts cannot work correctly on Github
- styles installed via userscript cannot be applied on Github

### PR DESCRIPTION
**Pull request by evilpie**
This fixes #173. And makes Violentmonkey work on recent builds of Firefox 58 on pages with CSP.

### CODE REVIEW

**Comment by eight04** [comment]
Would this work on Firefox 57?

**Comment by gera2ld** [comment]
That's great! Could you fix the lint errors? Maybe we should add `URL.revokeObjectURL` after using it.

**Comment by evilpie** [comment]
@gera2ld Fixed. We should definitely use revokeObjectURL to prevent leaks.

**Comment by gera2ld** [comment]
This has brought up a new problem, which breaks VM web page listeners on Chrome stable Win 10. But works on Chrome any Mac OS X, and Chrome canary Win 10. I think it's a bug of Chrome on Windows but should be fixed. See #249 .

**Pull request merged**
