### PR TITLE
Update tooltip style in dark mode

### PR DESCRIPTION
**Pull request by gera2ld**
image

## Collateral changes

- Add a link to contributors list instead of personal email

### CODE REVIEW

**Comment by tophf** [comment]
Mmm, I really liked the black tooltip in the dark mode. You don't?

**Comment by gera2ld** [comment]
> Mmm, I really liked the black tooltip in the dark mode. You don't?

The black tooltip in a dark background looks not so clear to me since the colors are similar. I can hardly tell where the arrow is and how large the box is.
So I need to lighten either the background color or the tooltip. After some investigation I took the style from Firefox, which looks good to me.

Snapshot from Firefox:
image

**Comment by tophf** [comment]
The arrow doesn't seem important to me as  the tooltip is close to the target, but the important thing for those who use the dark mode is, AFAIK, the overall ambiance, which is now disrupted by the bright tooltip. Firefox is even brighter and hence worse in my opinion. The black tooltip looked really slick and cool.

**Comment by tophf** [comment]
If you like the bright tooltip, maybe you could delay it so it doesn't flicker in the dark page on mouse movement:

```css
@keyframes fade-in {
  from { opacity: 0 }
  to { opacity: 1 }
}

body .vl-tooltip {
  animation: .25s fade-in .25s both;
}
```

**Comment by tophf** [comment]
BTW in my Windows the standard tooltip is dark:

image

The fact that it appears suddenly nearby is enough to draw my attention so I'm perfectly fine with its color being similar to the surroundings.

**Comment by gera2ld** [comment]
The light border makes it clearer. I'll see if I can keep the black background and add a light border.

**Comment by tophf** [comment]
The simplest way to add a border is probably `box-shadow`

**Comment by tophf** [comment]
Yay I like it but you wanted to enhance the arrow so maybe add the `border` there too?

**Comment by gera2ld** [comment]
The arrow itself is built with `border`s so it's not easy to add another `border` for it. I'll leave it as is. Does it look good to you?

**Comment by tophf** [comment]
Well, ideally I'd like the arrow to have a border. It can be handled separately though, I'm not a perfectionist.

**Comment by gera2ld** [comment]
Maybe I'll find a perfect way someday.

**Pull request merged**
