### PR TITLE
fix: update tooltip alignment to avoid overflow

### LINKED ISSUE #2036: [BUG] can not scroll script settings page
### Sequence of actions: 
1.Create a new script
2.Click Settings
3.Input strings to `@include rules` or expand input area

### Problem: 
Overflowed elements (`@match rules`,`@exclude rules`,`@exclude-match rules`) are not visible and cannot be scrolled "Settings" page.

### Expected result:  
Overflowed elements are not visible, but they can be scrolled "Settings" page.

#### Environment:
- OS: Windows
- Browser: Firefox 115.8.0esr
- Violentmonkey Version: v2.18.0 (BETA v2.15.9 and later)

### PR DESCRIPTION
**Pull request by gera2ld**
Close #2036

### CODE REVIEW

**Comment by tophf** [comment]
It also happens on `<` `>` buttons.

**Comment by tophf** [comment]
Actually align=end doesn't solve the problem when the button is wrapped to the left:
image

**Comment by gera2ld** [comment]
> Actually align=end doesn't solve the problem when the button is wrapped to the left

Yeah but fixing that requires a refactor of the tooltip component, I will just fix the most common cases here first.

**Comment by tophf** [comment]
Did you see my comment?

> It also happens on < > buttons.

**Comment by gera2ld** [comment]
Oh I thought I fixed 2 more buttons, just realized they were the replace buttons. Let me update.

**Pull request merged**
