### PR TITLE
fix: auto save only if there is no save button

### PR DESCRIPTION
**Pull request by gera2ld**
- make code a little more declarative
- change saving behavior a bit to make it more intuitive: reload page before clicking *Save* should discard unsaved changes

### CODE REVIEW

**Comment by tophf** [comment]
I think this is a pretty big change in behavior so to prevent the inadvertent loss of data you should add `beforeunload` event handler.

**Comment by gera2ld** [comment]
@tophf OK. It was a surprise to me that the save button did nothing. 😅

**Comment by tophf** [comment]
Yeah it was a side-effect. Still, I'm worried that many people may be relying on this auto-saving...

**Comment by gera2ld** [comment]
There are quite a few changes to apply the `beforeunload` sentry. I'll start a new PR for that.

**Comment by tophf** [comment]
This is why I wanted to keep the old behavior, to avoid all that :-)

**Comment by gera2ld** [comment]
But the old behavior is weird, isn't it?
Besides, I think it's reasonable to have a `beforeunload` sentry module since it's common and useful.

**Review by tophf — APPROVED** [review]

**Pull request merged**
