### PR TITLE
feat: separate cookies in gmXHR per container

### LINKED ISSUE #1167: Can leak incognito data
Now this only occurs with Super Preloader enabled, but I think a UserScripts manager should block this either way

Bug Report here: https://github.com/machsix/Super-preloader/issues/485

### PR DESCRIPTION
**Pull request by tophf**
Fixes #1167.

`Cookie` and `Set-Cookie` HTTP headers for incognito tabs in Chrome or all tabs in FF will use their own cookie store. Chrome has two (default and incognito), FF may have many additional containers.

Could you help test it, please, @AlttiRi, @brian6932? Here's a dev version: [dev.zip](https://github.com/violentmonkey/violentmonkey/files/6769437/dev.zip)

### CODE REVIEW

**Comment by AlttiRi** [comment]
What's about my issue: https://github.com/violentmonkey/violentmonkey/issues/1086

Okay, it fixes the second case with you have passed a captcha in the incognito window (and you have not passed in the common window).

But anyway it's not an alternative for `"incognito": "split"` mode, when you use a proxy extension in the incognito window (and it's disabled for the common window). (the first case of my issue.)

**Comment by tophf** [comment]
> What's about my issue: #1086

This PR doesn't try to imitate `incognito:split` mode.

**Comment by tophf** [comment]
@gera2ld, this code seems to work correctly with my scripts over the past few weeks so maybe you could take a look at the code?

**Review by gera2ld — APPROVED** [review]
LGTM

**Comment by brian6932** [comment]
Yea this solved the issue 👍

**Pull request merged**
