### PR TITLE
feat: add `isBlobUrl` parameter to GM_getResourceURL

### PR DESCRIPTION
**Pull request by tophf**
```js
GM_getResourceURL(name) // blob: URL
GM_getResourceURL(name, true) // blob: URL
GM_getResourceURL(name, false) // data: URL
```

### CODE REVIEW

**Comment by tophf** [comment]
I've simplified the PR: the second parameter is a boolean now, `true` (default) is a blob URL, otherwise it's a data URL.

**Review by gera2ld — APPROVED** [review]
LGTM

**Comment by lisonge** [comment]
isBlobUrl not work
image

**Comment by tophf** [comment]
@lisonge, it works since Violentmonkey v2.13.0.15, so you're probably using an old version.

**Pull request merged**
