### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
:-)

### CODE REVIEW

**Comment by tophf** [comment]
Please use [transifex](https://www.transifex.com/violentmonkey/violentmonkey-nex/) because currently Violentmonkey syncs translations only in one direction: from transifex.

**Comment by Vistaus** [comment]
Okay, I requested the Dutch language on Transifex :)

**Comment by tophf** [comment]
Yay, bidirectional sync with Transifex is finally here, #1036.

**Comment by Vistaus** [comment]
Cool! I also joined the Dutch team now and uploaded the translated strings, so I'll close this PR.

**Pull request closed without merging**
