### PR TITLE
feat: shift-del cuts entire line in FF

### PR DESCRIPTION
**Pull request by tophf**
Firefox-only.

Adds the convenient and pretty standard <kbd>Shift</kbd><kbd>Delete</kbd> to cut the entire line when nothing is selected.
Weirdly, FF implements this behavior in <kbd>Ctrl</kbd><kbd>X</kbd> and <kbd>Ctrl</kbd><kbd>Insert</kbd>.

### CODE REVIEW

**Comment by gera2ld** [comment]
Why is this implemented for Firefox? For me <kbd>Shift</kbd><kbd>Delete</kbd> doesn't work either in Chrome or Firefox, and I've never used such a shortcut before.
Isn't it normal to cut a line with <kbd>Ctrl</kbd><kbd>X</kbd> when nothing is selected? This is the way many IDEs or editors works AFAICT.

**Comment by tophf** [comment]
Apparently it's Windows only. It's a well-known standard Windows shortcut that was there for decades since the very first versions as well as Shift-Insert and Ctrl-Insert. I'll change the PR to Windows-only then.

**Comment by tophf** [comment]
It's also used in Linux GNOME/KDE: https://en.wikipedia.org/wiki/Cut,_copy,_and_paste#Common_keyboard_shortcuts

**Comment by gera2ld** [comment]
OK, it's not bad to have a standard shortcut, though I think <kbd>Ctrl</kbd><kbd>X</kbd> is much more convenient to press.

**Comment by tophf** [comment]
Oops, I almost forgot that it should work on multiple lines in multi-caret mode (when lines are selected via Ctrl-click).

**Comment by tophf** [comment]
>though I think CtrlX is much more convenient to press

A matter of habit. Pressing Shift-Del using the right hand which is resting around the arrow keys is super convenient as well.

**Comment by tophf** [comment]
I've [suggested this feature in CodeMirror repo](https://github.com/codemirror/CodeMirror/issues/6061). Let's wait for their response.

**Comment by tophf** [comment]
CM implemented a brilliant workaround so everyone will benefit with its next release.

**Pull request closed without merging**
