### PR TITLE
fix: dark mode theme of CodeMirror

### PR DESCRIPTION
**Pull request by gera2ld**
There is no `CodeMirror-wrap` in the codebase.

### CODE REVIEW

**Comment by tophf** [comment]
LGTM

**Comment by tophf** [comment]
BTW CodeMirror-wrap is added by CM itself but the old code was incorrect anyway because `.CodeMirror-wrap .CodeMirror` doesn't match anything since these two classes belong to the same element. It was broken recently by my #1069.

**Comment by gera2ld** [comment]
> CodeMirror-wrap is added by CM itself

Maybe something is changed in the latest CodeMirror because I could not find it in the DOM either, `document.querySelector('.CodeMirror-wrap')` gives `null`.

Screen Shot 2020-10-06 at 15 13 13

**Comment by tophf** [comment]
Oh, today I learned it's added only when line wrapping option is enabled... Previously I thought it's a class for the cm.display.wrapper element.

**Pull request merged**
