### PR TITLE
feat: add "exclude" to popup menu

### LINKED ISSUE #367: disable script in the popup for the current site
### What is the problem?
https://github.com/violentmonkey/violentmonkey/issues/366

### How to reproduce it?
1. disable single script with the popup panel

example. https://greasyfork.org/pl/scripts/30974-autoplay-disabled-for-html5-videos-pause-on-switch-tab

### What is the expected result?
blocked this script per this single site

### What is the actual result?
blocked this script per all sites

### Environment
- Browser: chrome
- Browser version: 64.0.3282.186
- Violentmonkey version: v2.8.29
- OS: win10

### PR DESCRIPTION
**Pull request by tophf**
Fixes #367.

<details><summary>Initial implementation, now rejected, see comments below</summary>

Menu | UI
-|-
image | image

</details>

### CODE REVIEW

**Comment by gera2ld** [comment]
I think a content-rich popup inside another popup looks weird.
How about rendering the form as a submenu instead of a popup so that we don't need to care about the height and position of the popup?

**Comment by tophf** [comment]
Indeed. Seems obvious now that you mention it :-) Gonna try.

**Comment by tophf** [comment]
image

And this is after clicking `(i)`

image

**Review by gera2ld — APPROVED** [review]
Great work! LGTM.

**Pull request merged**
