### PR TITLE
chore: publish release on tag push

### PR DESCRIPTION
**Pull request by gera2ld**
Publish to CWS if a release tag is created.

### CODE REVIEW

**Review by happymx — APPROVED** [review]

**Comment by tophf** [comment]
@gera2ld, are you merging this PR? I want to publish a new release now.

**Comment by tophf** [comment]
I meant a beta release, so maybe this PR is not necessary?

**Comment by gera2ld** [comment]
it's not necessary

**Comment by gera2ld** [comment]
It seems that self-distributed version on AMO also [requires source code review](https://extensionworkshop.com/documentation/publish/signing-and-distribution-overview/#distributing-your-addon) now, so the release process on AMO cannot be automatic any more. I think we can drop support for beta version for Firefox.

**Comment by tophf** [comment]
It doesn't say the submission is blocked until the check is performed.

**Comment by gera2ld** [comment]
But it's actually blocked.

image

**Comment by tophf** [comment]
Do you know if it's possible to include the source code when submitting automatically?

**Comment by gera2ld** [comment]
There is [a new API](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-sources) for this but no support in sign-addon yet. I'm trying to achieve this by using cURL directly.

**Comment by tophf** [comment]
Our version numbers are too long e.g. `2.13.10.1`. What about dropping one component? Next release: 2.14. Beta: 2.14.1.

**Comment by gera2ld** [comment]
> What about dropping one component?

Yep I agree.

**Pull request merged**
