### PR TITLE
Sort & filtering in popup

### PR DESCRIPTION
**Pull request by tophf**
Since I've never needed to care about the execution order in all the years I've been using userscripts I have a reason to believe the same applies to most users, at least to a lot of them, so this PR adds several options to display the scripts in the popup in a more human-friendly way, mostly useful when there are many scripts installed.

* alphabetical order (default: execution)
* enabled scripts first (default: false)
* disabled scripts hidden (default: false)

The default state preserves the historical behavior.

image

**Collateral change:**

* Removed the implicit space between the checkbox and its text in settings + aligned them vertically against each other.

### CODE REVIEW

**Comment by gera2ld** [comment]
It does not display well when lines wrap.

image

**Comment by tophf** [comment]
* Added `flex-wrap` on the last line.
* I don't see why vertical centering on the second line is a problem (IMO it looks fine).

**Comment by gera2ld** [comment]
> * I don't see why vertical centering on the second line is a problem (IMO it looks fine).

If there are a few lines of text beside a checkbox, it's hard to tell where to start. (I guess we don't want to add separator lines between them.)

```
[ ] first line
    second line
[ ] third line
    fourth line
```

Intuitively I would say `first line\nsecond line` is for the first checkbox, and `third line\nfourth line` is for the second checkbox. This is also the default behavior in lists (`<ul>`).
But if the checkbox is aligned in the middle, `second line\nthird line\nfourth line` should be the content of the second checkbox.

There could be different margins, but I still think it hard to find the start line at first sight.

**Comment by tophf** [comment]
The problem I was trying to solve is the bad vertical centering of checkboxes against the associated text label. It looks better when the text is not wrapped, which arguably constitutes 99% of use cases. I think the 1% of cases where it's wrapped due to narrow width can be ignored. Mm?

**Comment by tophf** [comment]
I'd rather rephrase the overly long labels e.g. "Reload the tab when toggling a script in the popup"

**Comment by gera2ld** [comment]
> I think the 1% of cases where it's wrapped due to narrow width can be ignored.

We support running on Firefox Android, so this is not the 1% of cases. Display on mobile devices is always taken into account.

**Comment by tophf** [comment]
Ah, indeed.
I've added a media restraint on min-width.

**Comment by tophf** [comment]
BTW extensions are also supported in mobile Chrome forks such as Yandex and Kiwi.

**Comment by gera2ld** [comment]
The style change here has some problems in other languages because of extra margins. I'm gonna fix it by removing the flex layout and keep white spaces as before.

**Comment by tophf** [comment]
What problems exactly? That space is a bug itself so a proper fix should remove it. An alternative method to flexbox is to start the next tag immediately, not on the next line, or use a comment:

```html
    <foo .....></foo><!--
 --><bar ...></bar>
```

**Comment by tophf** [comment]
There's an [option to strip spaces](https://github.com/vuejs/vue/tree/dev/packages/vue-template-compiler#options) in vue template compiler, which looks like it should help here and everywhere.

**Comment by gera2ld** [comment]
Some languages need space between words, e.g. English, and some not, e.g. Chinese. So it looks weird as `select { margin-left: .5em; }` is added. That's why I kept the white spaces in locale files.

After setting `font-size: 1rem` for `<select>`s and adding `vertical-align: middle`, it looks fine.
It's strange that I found many cases from StackOverflow seem to have worked in the past but do not work any more.

> There's an [option to strip spaces](https://github.com/vuejs/vue/tree/dev/packages/vue-template-compiler#options) in vue template compiler, which looks like it should help here and everywhere.

This option is already on. It seems that spaces are still kept in development mode, which might be a bug.

**Comment by gera2ld** [comment]
Bootstrap gave up on this alignment problem. 😃 https://github.com/twbs/bootstrap/issues/18797

**Comment by tophf** [comment]
I see `collapseWhitespace: true` and `preserveWhitespace: false` but the option I've linked is `whitespace: 'condense'` - is there any difference? I've tried adding it in [plaid-vue/webpack/vue.js](https://github.com/gera2ld/plaid/blob/d07a51149257ededd438dbe0d5f450d0d3b1e9d5/packages/plaid-vue/webpack/vue.js#L15) and it removed the space in dev build.

As for vertical-align, it was worsening things in Firefox when I tried it which is why I've used flexbox. Did you test your fix in FF?

**Comment by gera2ld** [comment]
I've tested in Chrome / Firefox / Vivaldi, trying to test in mobile.

**Comment by gera2ld** [comment]
@tophf I was wrong, I was using the deprecated `preserveWhitespace` option. I'll try the new one later.

**Pull request merged**
