### PR TITLE
make SafePromise.prototype.then unreplaceable

### PR DESCRIPTION
**Pull request by xBZZZZ**
https://github.com/violentmonkey/violentmonkey/issues/1432

### CODE REVIEW

**Comment by tophf** [comment]
I don't understand why changing a function reference affects the prototype, which we don't use. Can you demonstrate the bug?

**Comment by tophf** [comment]
Ah, I guess it's the same eval thing.

**Comment by xBZZZZ** [comment]
> I don't understand why changing a function reference affects the prototype, which we don't use. Can you demonstrate the bug?

`Object.freeze(obj)` freezes `obj` and returns `obj`
---
```javascript
Object.freeze(Promise.prototype).then;
```
does same thing as
```javascript
(function(){
  var pp=Promise.prototype;
  Object.freeze(pp);
  return pp.then;
})();
```

**Comment by tophf** [comment]
Yeah, I know. I just misread it the first time and thought you were freezing the function.

**Pull request merged**
